# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='album_logo',
            field=models.FileField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
