# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0004_auto_20171114_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('High_sc_board', models.CharField(default='', max_length=300)),
                ('Inter_sc_board', models.CharField(default='', max_length=300)),
                ('Undergraduate', models.CharField(default='', max_length=300)),
                ('Postgraduate', models.CharField(default='', max_length=300)),
                ('Phd', models.CharField(default='', max_length=300)),
                ('high_year', models.CharField(default='', max_length=100)),
                ('intermediate_year', models.CharField(default='', max_length=100)),
                ('Phd_year', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
