# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_projects_publications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Publications',
            new_name='Publication',
        ),
        migrations.RenameModel(
            old_name='Teachings',
            new_name='Teaching',
        ),
    ]
