# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 07:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0008_auto_20171115_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.CharField(default='', max_length=100)),
                ('end_year', models.CharField(default='', max_length=100)),
                ('About', models.CharField(default='', max_length=1000)),
                ('Reponsibilty', models.CharField(default='', max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
