# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='webmail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
