# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_profile_webmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.Profile'),
            preserve_default=False,
        ),
    ]
