# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_qualification_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='profile',
        ),
    ]
