# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20171117_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='Reponsibilty',
            new_name='Reponsibility',
        ),
    ]
