# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20171118_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='Reponsibility',
            new_name='Responsibility',
        ),
    ]
