# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_remove_qualification_phd_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
