# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20171118_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='High_sc_board',
            new_name='Postgraduate_college',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='Inter_sc_board',
            new_name='Undergraduate_college',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='high_year',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='intermediate_year',
        ),
        migrations.AddField(
            model_name='qualification',
            name='Phd_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualification',
            name='Postgraduate_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualification',
            name='Undergraduate_year',
            field=models.IntegerField(default=0),
        ),
    ]
