# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20171118_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='Phd_college',
            field=models.CharField(default='', max_length=300),
        ),
    ]
