# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_qualification_phd_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
