# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
