# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_auto_20171119_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Fax',
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(default='', max_length=300),
        ),
    ]
