# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20171119_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaching',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
