# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_teaching_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profile_image/', upload_to='profile_image'),
        ),
    ]
